version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[actions]"
    open-pull-requests-limit: 0

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[submodule]"
    open-pull-requests-limit: 0

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[docker]"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[npm]"
    open-pull-requests-limit: 0
