name: Deploy vitepress content to Pages

on:
  push:
    branches:
      - trunk

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write
  
# # Allow one concurrent deployment
# concurrency:
#   group: "pages"
#   cancel-in-progress: true

jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm ci
      - run: npm run build-docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          force_orphan: true
          # cname: example.com # if wanna deploy to custom domain
        env:
          CI: true
