name: Deploy vitepress content to Pages

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install OS Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y git cmake ninja-build wget zip
          sudo apt-get install -y gcc-multilib g++-multilib pkg-config autoconf bison libtool flex
          sudo apt-get install -y python3 python3-pip
          sudo apt-get install -y chromium

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install JS Dependencies
        run: |
          npm ci

      - name: Install CPP Dependencies
        run: |
          npm run install-build-deps

      - name: Build
        run: |
          npm run build

      - name: Build Docs
        run: |
          npm run build-docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          force_orphan: true
          # cname: example.com # if wanna deploy to custom domain
        env:
          CI: true

      - name: Upload error logs
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.node }}-logs
          path: |
            ./vcpkg/buildtrees/**/*.log
            ./build/**/*.log
