name: Test PR

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-13, macos-14]
        node: [18, 20, 22]

    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.os }}, node-${{ matrix.node }} sample
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"
          scope: "@hpcc-js"

      - name: Install Ubuntu Dependencies
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y git cmake ninja-build wget zip
          sudo apt-get install -y gcc-multilib g++-multilib pkg-config autoconf bison libtool flex
          sudo apt-get install -y python3 python3-pip

      - name: Install OSX Dependencies
        if: ${{ contains(matrix.os, 'macos') }}
        run: |
          brew install ninja flex bison automake autoconf-archive coreutils
          if [[ $(uname -m) == 'arm64' ]]; then
            echo "PATH=/opt/homebrew/opt/bison/bin:/opt/homebrew/opt/flex/bin:$PATH" >> $GITHUB_ENV
          else
            echo "PATH=/usr/local/opt/bison/bin:/opt/homebrew/opt/flex/bin:$PATH" >> $GITHUB_ENV
          fi
          bison --version

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: npm ci
        run: |
          bison --version
          npm ci

      - name: npx playwright install
        run: |
          npx playwright install --with-deps

      - name: install-build-deps
        run: |
          npm run install-build-deps

      - name: Lint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test

      - name: Calculate Coverage
        if: ${{ matrix.os == 'ubuntu-24.04' && matrix.node == 20 }}
        run: |
          npm run coverage

      - name: Upload error logs
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.node }}-logs
          path: |
            ./vcpkg/buildtrees/**/*.log
            ./build/**/*.log
