name: teast-and-publish

on: 
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          scope: "@hpcc-js"

      - name: Install OS Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y git cmake ninja-build wget zip
          sudo apt-get install -y gcc-multilib g++-multilib pkg-config autoconf bison libtool flex
          sudo apt-get install -y python3 python3-pip

      - name: Install Dependencies
        run: |
          npm ci
          npm run install-build-deps

      - name: Lint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build

      - name: Test
        env:
          CI: true
        run: |
            npm run test

      - name: Calculate Coverage
        run: |
          npm run coverage
          npm run coverage-report

      - name: Update Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Publish
        if: github.ref_type == 'tag'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm run publish

      - name: Purge jsdelivr
        if: github.ref_type == 'tag'
        run: |
          npm run purge-jsdelivr

      - name: Create Release
        if: github.ref_type == 'tag'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
